apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pharma-qa
  namespace: argocd
  labels:
    env: qa
    type: app-of-apps          # ← ADD this label
    managed-by: terraform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pharma
  source:
    repoURL: https://github.com/chavansb/zen-gitops.git
    targetRevision: HEAD
    path: argocd/apps/qa       # ← CHANGE from envs/qa to argocd/apps/qa
    # This folder contains child Application yamls
    # ArgoCD reads them and creates all 9 service Applications
  destination:
    server: https://kubernetes.default.svc
    # app-of-apps Application resource itself lives on DEV cluster
    # BUT child apps deploy TO qa cluster (defined in each child app)
    namespace: argocd          # ← CHANGE from qa to argocd
    # Application resources must live in argocd namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10