apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pharma-deployer
  namespace: dev
  labels:
    env: dev
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Replace YOUR_IAM_USERNAME with your AWS IAM username (e.g., john.doe)
# Run: kubectl get configmap aws-auth -n kube-system -o yaml  to find your username
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharma-deployer-binding
  namespace: dev
  labels:
    env: dev
subjects:
  - kind: User
    name: chandika
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pharma-deployer
  apiGroup: rbac.authorization.k8s.io
